### PR TITLE
Fix fleet creation messages, add FIXMEs

### PR DESCRIPTION
**Pull request by bernhardkaindl**
@klutchell Address #44: #43 (orignally #36) was a start but by far not complete.

This PR is just to show how much needs to be updated and to do provide the needed fixes I saw so far.

Daniel Borek of Balena wanted to know of any inconsistencies in documentation, so that is one for him:
https://youtu.be/NpMC2WWSpNI?t=3541

### CODE REVIEW

**Comment by rhampt** [comment]
@taromurao FYI, I think your previous PR is incomplete as @bernhardkaindl points out here!

**Comment by taromurao** [comment]
@rhampt JFYI, my PR was actually a copy and paste of another PR. It was just a workaround of the problem that the original PR issuer had problems in getting the PR merged. That being said, I am happy to create another PR with @bernhardkaindl and close mentioned issues. Can you just move this PR branch to balena-io/balena-cli-advanced-masterclass, it would be then easier to modify and comment. As far as I could read from general balena contribution guide, creating a branch directly in the project repository would be also correct. What do you think?
And sorry for my belated response. I hope, I can process quicker with next iterations.

**Comment by bernhardkaindl** [comment]
@taromurao When I try to push to a new branch of this repo, I get and error:
`ERROR: Permission to balena-io/balena-cli-advanced-masterclass.git denied to bernhardkaindl.`

This because I am not a member of this balena-io project so far.

I invited you as an admin to https://github.com/openbalena/[balena-cli-advanced-masterclass](https://github.com/openbalena/balena-cli-advanced-masterclass) so you can fully update the branch of the PR as you like.

Do you or @rhampt have write permission to https://github.com/balena-io/balena-cli-advanced-masterclass to merge the PR then?

**Comment by rhampt** [comment]
Hi @bernhardkaindl — Rather than merge this PR with the #FIXME 's , I'm going to go back through the masterclass and update it based on all recent changes so it's more clear going forward. I appreciate you asking about this, it is rather out of date!

**Pull request closed without merging**
